import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

const KEYWORDS = [
  ['JavaScript','language',10,['backend','frontend','fullstack','mobile'],['js','javascript','ecmascript','es6','es2015','vanilla js','vanilla javascript']],
  ['TypeScript','language',10,['backend','frontend','fullstack','mobile'],['ts','typescript','ts lang']],
  ['Python','language',10,['backend','ai','fullstack','data'],['python3','python 3','py','python2','cpython']],
  ['Java','language',9,['backend','mobile','fullstack'],['java se','java ee','core java','java programming']],
  ['Go','language',9,['backend','devops'],['golang','go lang','go programming']],
  ['Rust','language',8,['backend','devops'],['rust lang','rust programming','rustlang']],
  ['C++','language',8,['backend','ai'],['cpp','c plus plus','cplusplus','c++11','c++17']],
  ['C','language',7,['backend'],['c lang','c programming','ansi c']],
  ['C#','language',8,['backend','mobile'],['csharp','c sharp','dotnet csharp']],
  ['Kotlin','language',8,['mobile','backend'],['kotlin lang','kotlin programming']],
  ['Swift','language',8,['mobile'],['swift lang','swift programming']],
  ['PHP','language',7,['backend','fullstack'],['php7','php8','php lang']],
  ['Ruby','language',7,['backend'],['ruby lang','ruby programming']],
  ['Scala','language',7,['backend','data'],['scala lang','scala programming']],
  ['R','language',7,['ai','data'],['r lang','r programming','r statistical']],
  ['Dart','language',7,['mobile'],['dart lang','dart programming']],
  ['Elixir','language',6,['backend'],['elixir lang','elixir programming']],
  ['SQL','language',9,['backend','fullstack','data','ai'],['structured query language','sql queries','sql programming']],
  ['HTML','language',8,['frontend','fullstack'],['html5','html 5','hypertext markup']],
  ['CSS','language',8,['frontend','fullstack'],['css3','css 3','cascading style','stylesheet']],
  ['Bash','language',7,['backend','devops'],['bash scripting','shell scripting','bash script','shell script','zsh']],
  ['MATLAB','language',6,['ai','data'],['matlab programming']],
  ['Solidity','language',6,['backend'],['solidity lang','smart contracts lang']],
  ['Julia','language',6,['ai','data'],['julia lang','julia programming']],
  ['Node.js','framework',10,['backend','fullstack'],['nodejs','node js','node.js runtime','node runtime']],
  ['Express.js','framework',9,['backend','fullstack'],['express','expressjs','express js','express framework']],
  ['Fastify','framework',8,['backend'],['fastify framework','fastify.js']],
  ['Hono','framework',7,['backend'],['hono.js','hono framework']],
  ['NestJS','framework',8,['backend','fullstack'],['nestjs','nest js','nest.js','nest framework']],
  ['Koa','framework',6,['backend'],['koa.js','koajs','koa framework']],
  ['Django','framework',9,['backend','fullstack'],['django framework','django rest','django python']],
  ['Flask','framework',8,['backend','ai'],['flask framework','flask python','flask api']],
  ['FastAPI','framework',9,['backend','ai'],['fast api','fastapi python']],
  ['Spring Boot','framework',9,['backend'],['springboot','spring-boot','spring boot java']],
  ['Spring','framework',8,['backend'],['spring framework','spring mvc','spring security']],
  ['Laravel','framework',7,['backend'],['laravel php','laravel framework']],
  ['Ruby on Rails','framework',7,['backend'],['rails','ror','ruby rails','rails framework']],
  ['Gin','framework',7,['backend'],['gin framework','gin golang','gin-gonic']],
  ['Fiber','framework',6,['backend'],['fiber framework','fiber golang','gofiber']],
  ['Actix','framework',6,['backend'],['actix-web','actix web','actix rust']],
  ['Axum','framework',6,['backend'],['axum framework','axum rust']],
  ['tRPC','framework',7,['backend','fullstack'],['trpc','t3 stack','type-safe rpc']],
  ['gRPC','framework',8,['backend'],['grpc','google rpc','protocol buffers rpc']],
  ['GraphQL','framework',8,['backend','fullstack'],['graph ql','graphql api','graphql server']],
  ['.NET','framework',8,['backend'],['dotnet','.net core','asp.net','aspnet','asp.net core']],
  ['React','framework',10,['frontend','fullstack','mobile'],['reactjs','react.js','react js','react library']],
  ['Next.js','framework',10,['frontend','fullstack'],['nextjs','next js','next framework']],
  ['Vue.js','framework',9,['frontend','fullstack'],['vue','vuejs','vue js','vue framework']],
  ['Nuxt.js','framework',8,['frontend','fullstack'],['nuxt','nuxtjs','nuxt js','nuxt framework']],
  ['Angular','framework',9,['frontend','fullstack'],['angularjs','angular js','angular framework','angular cli']],
  ['Svelte','framework',8,['frontend'],['sveltejs','svelte js','sveltekit','svelte kit']],
  ['SvelteKit','framework',8,['frontend','fullstack'],['svelte kit framework']],
  ['Remix','framework',7,['frontend','fullstack'],['remix.run','remix framework','remix js']],
  ['Astro','framework',7,['frontend'],['astro.build','astro framework','astro js']],
  ['Gatsby','framework',6,['frontend'],['gatsby.js','gatsbyjs','gatsby framework']],
  ['Solid.js','framework',6,['frontend'],['solidjs','solid js','solid framework']],
  ['HTMX','framework',5,['frontend'],['htmx framework','html over the wire']],
  ['Tailwind CSS','framework',9,['frontend','fullstack'],['tailwind','tailwindcss']],
  ['Bootstrap','framework',7,['frontend','fullstack'],['bootstrap css','bootstrap framework','bootstrap 5']],
  ['Material UI','framework',7,['frontend'],['mui','material-ui','materialui']],
  ['Chakra UI','framework',6,['frontend'],['chakraui','chakra ui']],
  ['Ant Design','framework',6,['frontend'],['antd','ant design','antdesign']],
  ['Shadcn UI','framework',7,['frontend'],['shadcn','shadcn/ui']],
  ['Radix UI','framework',6,['frontend'],['radixui','radix ui']],
  ['SASS','framework',6,['frontend'],['scss','sass css','sass/scss']],
  ['Styled Components','framework',6,['frontend'],['styled-components','styled components css']],
  ['Redux','framework',7,['frontend','fullstack'],['redux toolkit','redux js','rtk','react redux']],
  ['Zustand','framework',7,['frontend'],['zustand state','zustand store']],
  ['Jotai','framework',6,['frontend'],['jotai state','jotai atoms']],
  ['React Query','framework',7,['frontend','fullstack'],['tanstack query','react-query','tanstack-query']],
  ['SWR','framework',6,['frontend'],['swr hooks','swr fetch']],
  ['Framer Motion','framework',6,['frontend'],['framer-motion','framer motion animation']],
  ['Three.js','framework',6,['frontend'],['threejs','three js','webgl three']],
  ['D3.js','framework',7,['frontend','data'],['d3','d3js','data visualization d3']],
  ['Webpack','framework',7,['frontend'],['webpack bundler','webpack config']],
  ['Vite','framework',8,['frontend','fullstack'],['vite bundler','vite build']],
  ['Storybook','framework',6,['frontend'],['storybook ui','component storybook']],
  ['React Native','framework',9,['mobile'],['react-native','react native app','rn']],
  ['Flutter','framework',9,['mobile'],['flutter app','flutter dart','flutter framework']],
  ['Expo','framework',7,['mobile'],['expo sdk','expo react native']],
  ['SwiftUI','framework',8,['mobile'],['swift ui','swiftui framework']],
  ['Jetpack Compose','framework',8,['mobile'],['jetpack','compose android','android compose']],
  ['Android SDK','framework',7,['mobile'],['android development','android sdk','android studio']],
  ['iOS SDK','framework',7,['mobile'],['ios development','ios sdk','xcode']],
  ['Ionic','framework',6,['mobile'],['ionic framework','ionic app']],
  ['PostgreSQL','database',10,['backend','fullstack','data'],['postgres','pg','psql','postgresdb']],
  ['MySQL','database',9,['backend','fullstack'],['mysql db','mysql server','mysql database']],
  ['MongoDB','database',9,['backend','fullstack'],['mongo','mongodb db','nosql mongo']],
  ['Redis','database',9,['backend','fullstack'],['redis cache','redis db','redis server','upstash']],
  ['SQLite','database',7,['backend','mobile'],['sqlite db','sqlite3']],
  ['Supabase','database',8,['backend','fullstack'],['supabase db','supabase postgres']],
  ['Firebase','database',8,['backend','fullstack','mobile'],['firebase db','firestore','firebase realtime']],
  ['DynamoDB','database',8,['backend'],['dynamo db','aws dynamodb','dynamodb nosql']],
  ['Cassandra','database',7,['backend','data'],['apache cassandra','cassandra db']],
  ['Elasticsearch','database',8,['backend','data'],['elastic search','elasticsearch db','opensearch','elk']],
  ['CockroachDB','database',7,['backend'],['cockroach db']],
  ['PlanetScale','database',7,['backend'],['planet scale','planetscale mysql']],
  ['Neon','database',7,['backend'],['neon db','neon postgres','neondb']],
  ['Turso','database',6,['backend','mobile'],['turso db','turso sqlite']],
  ['Oracle','database',7,['backend'],['oracle db','oracle database','oracle sql']],
  ['Microsoft SQL Server','database',7,['backend'],['mssql','sql server','ms sql','sqlserver']],
  ['MariaDB','database',7,['backend'],['maria db','mariadb mysql']],
  ['Neo4j','database',7,['backend','ai'],['neo4j db','graph database','cypher query']],
  ['Pinecone','database',8,['ai'],['pinecone vector','pinecone db']],
  ['Weaviate','database',7,['ai'],['weaviate vector','weaviate db']],
  ['Chroma','database',7,['ai'],['chromadb','chroma db','chroma vector']],
  ['FAISS','database',7,['ai'],['faiss index','facebook faiss','faiss vector']],
  ['Qdrant','database',6,['ai'],['qdrant vector','qdrant db']],
  ['Milvus','database',6,['ai'],['milvus vector','milvus db']],
  ['Prisma','tool',9,['backend','fullstack'],['prisma orm','prisma client','prisma db']],
  ['Drizzle','tool',8,['backend','fullstack'],['drizzle orm','drizzle-orm','drizzle db']],
  ['Mongoose','tool',8,['backend','fullstack'],['mongoose orm','mongoose mongodb']],
  ['Sequelize','tool',7,['backend'],['sequelize orm','sequelize js']],
  ['TypeORM','tool',7,['backend'],['typeorm','type orm']],
  ['SQLAlchemy','tool',8,['backend','ai'],['sqlalchemy orm','sqlalchemy python']],
  ['Hibernate','tool',6,['backend'],['hibernate orm','hibernate java']],
  ['GORM','tool',6,['backend'],['gorm golang','gorm go']],
  ['AWS','cloud',10,['backend','devops','fullstack'],['amazon web services','aws cloud','amazon aws']],
  ['GCP','cloud',9,['backend','devops'],['google cloud','google cloud platform']],
  ['Azure','cloud',9,['backend','devops'],['microsoft azure','azure cloud','ms azure']],
  ['Docker','tool',10,['backend','devops','fullstack'],['docker container','dockerfile','docker compose','docker-compose']],
  ['Kubernetes','tool',9,['devops','backend'],['k8s','kube','kubernetes cluster']],
  ['Terraform','tool',8,['devops'],['terraform iac','hashicorp terraform']],
  ['Ansible','tool',7,['devops'],['ansible playbook','ansible automation']],
  ['Jenkins','tool',7,['devops'],['jenkins ci','jenkins pipeline']],
  ['GitHub Actions','tool',8,['devops','fullstack'],['github-actions','gh actions','github workflows','gha']],
  ['GitLab CI','tool',7,['devops'],['gitlab-ci','gitlab ci/cd','gitlab pipeline']],
  ['CircleCI','tool',6,['devops'],['circle ci','circleci pipeline']],
  ['ArgoCD','tool',7,['devops'],['argocd','argo cd','argo gitops']],
  ['Helm','tool',7,['devops'],['helm charts','helm kubernetes']],
  ['Prometheus','tool',7,['devops'],['prometheus monitoring']],
  ['Grafana','tool',7,['devops'],['grafana dashboard','grafana monitoring']],
  ['Nginx','tool',8,['backend','devops'],['nginx server','nginx proxy','nginx config']],
  ['Vercel','cloud',8,['frontend','fullstack'],['vercel deploy','vercel hosting']],
  ['Netlify','cloud',7,['frontend','fullstack'],['netlify deploy','netlify hosting']],
  ['Heroku','cloud',6,['backend','fullstack'],['heroku deploy','heroku platform']],
  ['Render','cloud',6,['backend','fullstack'],['render.com','render deploy']],
  ['Railway','cloud',6,['backend','fullstack'],['railway.app','railway deploy']],
  ['DigitalOcean','cloud',6,['backend','devops'],['digital ocean','do droplet','digitalocean droplet']],
  ['Cloudflare','cloud',7,['backend','devops','fullstack'],['cloudflare workers','cf workers']],
  ['AWS Lambda','cloud',8,['backend','devops'],['lambda functions','serverless lambda','aws serverless']],
  ['AWS S3','cloud',8,['backend'],['s3 bucket','amazon s3','s3 storage']],
  ['AWS EC2','cloud',7,['backend','devops'],['ec2 instance','amazon ec2']],
  ['AWS RDS','cloud',7,['backend'],['rds database','amazon rds']],
  ['Linux','tool',8,['backend','devops'],['linux os','unix','ubuntu','debian','centos']],
  ['CI/CD','concept',8,['devops','backend'],['ci cd','continuous integration','continuous deployment','continuous delivery']],
  ['Kafka','tool',9,['backend','data','devops'],['apache kafka','kafka streaming','kafka broker','kafka queue']],
  ['RabbitMQ','tool',8,['backend'],['rabbitmq broker','rabbit mq','amqp']],
  ['AWS SQS','tool',7,['backend','devops'],['sqs queue','amazon sqs']],
  ['Celery','tool',7,['backend','ai'],['celery tasks','celery python','celery worker']],
  ['BullMQ','tool',6,['backend'],['bullmq','bull mq','bull queue','bull redis']],
  ['JWT','concept',9,['backend','fullstack'],['json web token','jwt auth','jwt tokens']],
  ['OAuth','concept',8,['backend','fullstack'],['oauth2','oauth 2.0','oauth authentication']],
  ['Authentication','concept',8,['backend','fullstack'],['auth','authentication system','user auth']],
  ['Authorization','concept',7,['backend','fullstack'],['rbac','role based access','permissions']],
  ['NextAuth','tool',7,['frontend','fullstack'],['next-auth','nextauth.js','next auth']],
  ['Auth0','tool',7,['backend','fullstack'],['auth0 auth','auth zero']],
  ['Clerk','tool',7,['frontend','fullstack'],['clerk auth','clerk.dev']],
  ['Bcrypt','tool',7,['backend'],['bcryptjs','bcrypt hashing','password hashing']],
  ['Rate Limiting','concept',6,['backend'],['rate limit','throttling','api rate limit']],
  ['Jest','tool',8,['backend','frontend','fullstack'],['jest testing','jest js','jest framework']],
  ['Vitest','tool',7,['frontend','fullstack'],['vitest testing','vitest framework']],
  ['Cypress','tool',7,['frontend'],['cypress e2e','cypress testing','cypress io']],
  ['Playwright','tool',7,['frontend'],['playwright testing','microsoft playwright']],
  ['Mocha','tool',6,['backend'],['mocha testing','mocha js','mocha framework']],
  ['PyTest','tool',7,['backend','ai'],['pytest','py test','pytest framework']],
  ['React Testing Library','tool',7,['frontend'],['rtl','testing library','@testing-library']],
  ['Unit Testing','concept',7,['backend','frontend','fullstack'],['unit tests','unit test','tdd','test driven']],
  ['Integration Testing','concept',7,['backend'],['integration tests','api testing']],
  ['TDD','concept',6,['backend','frontend'],['test driven development','test-driven']],
  ['Git','tool',10,['backend','frontend','fullstack','devops'],['git version control','git vcs','source control']],
  ['GitHub','tool',9,['backend','frontend','fullstack'],['github.com','github repo','github platform']],
  ['GitLab','tool',7,['backend','devops'],['gitlab.com','gitlab repo']],
  ['Postman','tool',7,['backend','fullstack'],['postman api','postman testing','api testing postman']],
  ['Swagger','tool',7,['backend'],['swagger ui','openapi','swagger docs','api docs']],
  ['Figma','tool',7,['frontend'],['figma design','figma ui','figma prototype']],
  ['Bun','tool',7,['backend','fullstack'],['bun runtime','bun.sh','bun js']],
  ['Deno','tool',6,['backend'],['deno runtime','deno.land']],
  ['ESLint','tool',6,['frontend','fullstack'],['eslint config','eslint rules']],
  ['Prettier','tool',6,['frontend','fullstack'],['prettier format','prettier config']],
  ['Turbo','tool',6,['fullstack'],['turborepo','turbo repo','monorepo turbo']],
  ['Microservices','concept',9,['backend','devops'],['microservice architecture','micro services']],
  ['REST API','concept',10,['backend','fullstack'],['restful api','rest apis','restful','rest endpoint','rest service']],
  ['API Design','concept',8,['backend','fullstack'],['api development','api architecture','api first']],
  ['System Design','concept',8,['backend'],['systems design','distributed systems','system architecture']],
  ['Scalability','concept',7,['backend'],['horizontal scaling','vertical scaling','scalable']],
  ['Caching','concept',7,['backend','fullstack'],['cache','caching strategy','cache layer']],
  ['Load Balancing','concept',7,['backend','devops'],['load balancer','lb','load balance']],
  ['WebSockets','concept',7,['backend','fullstack'],['websocket','ws protocol','socket.io','socketio','real-time']],
  ['Event-Driven','concept',7,['backend'],['event driven architecture','eda','event sourcing']],
  ['CQRS','concept',6,['backend'],['command query','command query responsibility']],
  ['MVC','concept',6,['backend','fullstack'],['model view controller','mvc pattern','mvc architecture']],
  ['DDD','concept',6,['backend'],['domain driven design','domain-driven']],
  ['Serverless','concept',7,['backend','devops'],['serverless functions','faas','function as a service']],
  ['Database Design','concept',7,['backend','fullstack'],['schema design','db design','database schema','erd']],
  ['OOP','concept',7,['backend'],['object oriented','object-oriented programming','solid principles']],
  ['Machine Learning','concept',10,['ai','data'],['ml','machine learning algorithms','ml models','supervised learning']],
  ['Deep Learning','concept',9,['ai'],['dl','neural network training','deep neural','deep learning models']],
  ['Neural Networks','concept',9,['ai'],['neural net','ann','artificial neural network']],
  ['TensorFlow','framework',9,['ai'],['tensorflow2','tf','tensor flow']],
  ['PyTorch','framework',9,['ai'],['pytorch','py torch','torch nn']],
  ['Keras','framework',8,['ai'],['keras api','keras layers','keras sequential']],
  ['scikit-learn','framework',8,['ai','data'],['sklearn','scikit learn','scikit_learn','sk-learn']],
  ['NumPy','framework',8,['ai','data'],['numpy','np array','numpy arrays']],
  ['Pandas','framework',8,['ai','data'],['pandas df','pandas dataframe','pd dataframe']],
  ['Matplotlib','framework',7,['ai','data'],['matplotlib plots','plt plots','pyplot']],
  ['OpenCV','framework',7,['ai'],['cv2','open cv','opencv python']],
  ['NLP','concept',9,['ai'],['natural language processing','nlp tasks','text processing']],
  ['Computer Vision','concept',8,['ai'],['cv','image recognition','object detection','image classification']],
  ['LLM','concept',9,['ai'],['large language model','llms','language model','foundation model']],
  ['GPT','concept',8,['ai'],['gpt-4','gpt4','gpt-3','chatgpt','openai gpt']],
  ['BERT','concept',7,['ai'],['bert model','bert nlp','google bert']],
  ['Transformers','concept',8,['ai'],['transformer model','attention model','hugging face transformers']],
  ['Hugging Face','tool',8,['ai'],['huggingface','hf transformers','hugging-face']],
  ['LangChain','framework',9,['ai'],['lang chain','langchain framework','langchain python']],
  ['LlamaIndex','framework',7,['ai'],['llama index','llamaindex','llama-index']],
  ['RAG','concept',9,['ai'],['retrieval augmented generation','retrieval-augmented','rag pipeline']],
  ['Vector Database','concept',8,['ai'],['vector db','vector store','embedding store','vector search']],
  ['Embeddings','concept',8,['ai'],['word embeddings','text embeddings','semantic embeddings','vector embeddings']],
  ['OpenAI','tool',8,['ai','fullstack'],['openai api','chatgpt api','gpt api']],
  ['Anthropic','tool',7,['ai'],['claude','anthropic api','claude api']],
  ['Ollama','tool',7,['ai'],['ollama local','local llm','ollama models']],
  ['Prompt Engineering','concept',8,['ai'],['prompting','prompt design','prompt tuning','chain of thought']],
  ['Fine-tuning','concept',7,['ai'],['model fine-tuning','finetune','finetuning','lora','qlora']],
  ['MLOps','concept',7,['ai','devops'],['ml ops','mlops pipeline','model deployment ops']],
  ['Data Science','concept',8,['ai','data'],['data scientist','data science analysis']],
  ['Feature Engineering','concept',7,['ai','data'],['feature extraction','feature selection']],
  ['A/B Testing','concept',7,['ai','data','fullstack'],['ab test','a/b test','split testing']],
  ['Statistics','concept',7,['ai','data'],['statistical analysis','probability statistics']],
  ['Apache Spark','framework',8,['data','ai'],['pyspark','spark dataframe','spark sql']],
  ['Airflow','tool',8,['data','devops'],['apache airflow','airflow dags','airflow pipeline']],
  ['dbt','tool',7,['data'],['dbt models','data build tool','dbt analytics']],
  ['Snowflake','database',7,['data'],['snowflake dw','snowflake cloud']],
  ['BigQuery','database',7,['data','ai'],['google bigquery','bq','bigquery sql']],
  ['Databricks','tool',7,['data','ai'],['databricks platform','databricks spark']],
  ['ETL','concept',7,['data'],['extract transform load','data pipeline','data ingestion']],
  ['Jupyter','tool',7,['ai','data'],['jupyter notebook','jupyter lab','ipynb']],
  ['Agile','concept',6,['backend','frontend','fullstack'],['agile methodology','agile development','agile scrum']],
  ['Scrum','concept',6,['backend','frontend','fullstack'],['scrum methodology','scrum master','scrum sprint']],
  ['Performance Optimization','concept',7,['backend','frontend'],['perf optimization','performance tuning']],
  ['Responsive Design','concept',7,['frontend'],['responsive web','mobile responsive','media queries']],
  ['Accessibility','concept',6,['frontend'],['a11y','wcag','web accessibility','aria']],
  ['SEO','concept',6,['frontend','fullstack'],['search engine optimization','seo optimization']],
  ['PWA','concept',6,['frontend'],['progressive web app','service worker','web manifest']],
  ['SSR','concept',7,['frontend','fullstack'],['server side rendering','server-side rendering']],
  ['Open Source','concept',6,['backend','frontend','fullstack'],['open source contribution','oss','github contributions']],
  ['Monorepo','concept',6,['fullstack'],['mono repo','monorepo architecture']],
  ['WebGL','framework',6,['frontend'],['web gl','webgl graphics']],
  ['Seaborn','framework',6,['ai','data'],['seaborn plots','seaborn visualization']],
  ['Plotly','framework',6,['ai','data'],['plotly charts','plotly visualization']],
  ['Hadoop','framework',6,['data'],['hdfs','mapreduce','hadoop cluster']],
  ['Tableau','tool',6,['data'],['tableau dashboard','tableau visualization']],
  ['Power BI','tool',6,['data'],['powerbi','power bi dashboard','microsoft power bi']],
  ['NATS','tool',6,['backend'],['nats messaging','nats server']],
  ['Sidekiq','tool',6,['backend'],['sidekiq jobs','sidekiq ruby']],
  ['Passport.js','tool',6,['backend'],['passport auth','passportjs']],
  ['SSL/TLS','concept',7,['backend','devops'],['ssl','tls','https','ssl certificate']],
  ['CORS','concept',6,['backend','fullstack'],['cross origin','cors headers']],
  ['CSRF','concept',5,['backend'],['csrf protection','cross site request']],
  ['Infrastructure as Code','concept',7,['devops'],['iac','infra as code']],
  ['Pulumi','tool',6,['devops'],['pulumi iac','pulumi infrastructure']],
  ['Message Queue','concept',7,['backend'],['message queuing','mq','async messaging']],
  ['Clean Architecture','concept',6,['backend'],['clean arch','onion architecture','hexagonal architecture']],
  ['Knockout.js','framework',4,['frontend'],['knockoutjs','knockout js']],
  ['Backbone.js','framework',4,['frontend'],['backbonejs','backbone js']],
  ['Ember.js','framework',5,['frontend'],['emberjs','ember js','ember framework']],
  ['Alpine.js','framework',5,['frontend'],['alpinejs','alpine js']],
  ['Stencil','framework',5,['frontend'],['stenciljs','stencil js']],
  ['Nx','tool',6,['fullstack'],['nx monorepo','nx workspace']],
  ['Recoil','framework',5,['frontend'],['recoil state','recoil js']],
  ['Kodein','tool',5,['mobile'],['kodein di','kodein kotlin']],
  ['Xamarin','framework',5,['mobile'],['xamarin forms']],
  ['Capacitor','framework',6,['mobile'],['capacitorjs','capacitor framework']],
  ['UIKit','framework',7,['mobile'],['ui kit ios','uikit framework']],
  ['Knex.js','tool',6,['backend'],['knex','knexjs','knex query builder']],
  ['Kysely','tool',6,['backend'],['kysely query','kysely builder']],
]

async function seed() {
  console.log(`🌱 Seeding ${KEYWORDS.length} keywords...`)

  // Clear existing (for re-runs)
  await prisma.keywordAlias.deleteMany()
  await prisma.keywordDomain.deleteMany()
  await prisma.keyword.deleteMany()
  console.log('  Cleared existing keywords')

  // Insert all keywords
  await prisma.keyword.createMany({
    data: KEYWORDS.map(([keyword, category, weight]) => ({ keyword, category, weight })),
    skipDuplicates: true,
  })
  console.log('  ✓ Keywords inserted')

  // Fetch all back to get IDs
  const kwMap = new Map()
  const all = await prisma.keyword.findMany({ select: { id: true, keyword: true } })
  for (const k of all) kwMap.set(k.keyword, k.id)

  // Build domain + alias rows
  const domainRows = []
  const aliasRows  = []
  const seenAliases = new Set()

  for (const [keyword,, , domains, aliases] of KEYWORDS) {
    const id = kwMap.get(keyword)
    if (!id) continue
    for (const domain of domains) {
      domainRows.push({ keywordId: id, domain })
    }
    for (const alias of aliases) {
      if (!seenAliases.has(alias)) {
        seenAliases.add(alias)
        aliasRows.push({ keywordId: id, alias })
      }
    }
  }

  // Batch insert domains + aliases
  const CHUNK = 500
  for (let i = 0; i < domainRows.length; i += CHUNK) {
    await prisma.keywordDomain.createMany({ data: domainRows.slice(i, i + CHUNK), skipDuplicates: true })
  }
  console.log(`  ✓ ${domainRows.length} domain mappings inserted`)

  for (let i = 0; i < aliasRows.length; i += CHUNK) {
    await prisma.keywordAlias.createMany({ data: aliasRows.slice(i, i + CHUNK), skipDuplicates: true })
  }
  console.log(`  ✓ ${aliasRows.length} aliases inserted`)

  const total = await prisma.keyword.count()
  console.log(`\n✅ Done — ${total} keywords in database`)
}

seed()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
