/**
 * aggregatorAgent.js
 *
 * Phase 6 — Structured Response
 *
 * Returns a clean two-part response:
 *   deterministicAnalysis → all scores from Rule Engine (numbers, facts)
 *   aiAnalysis            → all AI explanations (text, recommendations)
 *
 * IMPORTANT: Does NOT calculate any scores.
 * All numbers come from the Rule Engine.
 */

export const buildFinalReport = (resume, analysis, scores, aiReport) => {
  const { ats, recruiter, grammar, skills, projects } = aiReport;

  return {

    // ── PART 1: Deterministic Analysis ───────────────────────
    // Everything here is calculated by the Rule Engine — no AI.
    // These numbers are reliable and consistent.

    deterministicAnalysis: {

      // Final scores
      overall:  scores.overall,
      atsScore: scores.atsScore,
      label:    scores.label,

      // Section-by-section score breakdown
      breakdown: scores.breakdown,

      // Max possible per section (for progress bars)
      maxBreakdown: scores.maxBreakdown,

      // Candidate basic info
      candidate: {
        name:  resume.name  || 'Unknown',
        email: resume.email || '',
        phone: resume.phone || '',
      },

      // Top issues driving the score down
      deductions: scores.topDeductions.map(d => d.reason),

      // Intelligence Engine facts
      intelligence: {
        domain:           analysis.keywords.detectedDomain,
        keywordCoverage:  analysis.keywords.coveragePercent,
        coverageByDomain: analysis.keywords.coverage,
        matchedKeywords:  analysis.keywords.matchedKeywords,
        missingKeywords:  analysis.keywords.missingKeywords.slice(0, 10),
        skillCategories:  analysis.skills.categorized,
        totalSkills:      analysis.summary.totalSkills,
        totalProjects:    analysis.summary.totalProjects,
        totalExperience:  analysis.summary.totalExperience,
        projectScores:    (analysis.projects.projects || []).map(p => ({
          title:    p.title,
          score:    p.score,
          maxScore: p.maxScore,
          issues:   p.issues,
        })),
      },

      // Actionable steps from Rule Engine (no AI)
      actionableSteps: generateActionableSteps(scores, analysis),
    },

    // ── PART 2: AI Analysis ───────────────────────────────────
    // Everything here is generated by AI agents.
    // AI explains WHY, recommends WHAT, never calculates scores.

    aiAnalysis: {

      ats: {
        scoreExplanation:          ats.score_explanation             || '',
        issues:                    ats.ats_issues                    || [],
        keywordRecommendations:    ats.keyword_recommendations       || [],
        formattingRecommendations: ats.formatting_recommendations    || [],
        quickWins:                 ats.quick_wins                    || [],
      },

      recruiter: {
        summary:            recruiter.summary             || '',
        strengths:          recruiter.strengths           || [],
        weaknesses:         recruiter.weaknesses          || [],
        standoutPoints:     recruiter.standout_points     || [],
        redFlags:           recruiter.red_flags           || [],
        interviewReadiness: recruiter.interview_readiness || 'needs_work',
      },

      grammar: {
        errors:             grammar.errors                || [],
        suggestions:        grammar.writing_suggestions   || [],
        tone:               grammar.tone                  || 'professional',
        tenseConsistent:    grammar.tense_consistent      ?? true,
        writingQuality:     grammar.overall_writing_quality || 'average',
      },

      skills: {
        missingSkills:   skills.missing_skills   || [],
        learningRoadmap: skills.learning_roadmap || [],
        quickWins:       skills.quick_wins       || [],
        longTermGoals:   skills.long_term_goals  || [],
      },

      projects: {
        suggestions:         projects.project_suggestions  || [],
        recommendedProjects: projects.recommended_projects || [],
        quickWins:           projects.quick_wins           || [],
      },
    },
  };
};

/**
 * generateActionableSteps
 * Top 5 steps derived from Rule Engine deductions — no AI needed.
 */
const generateActionableSteps = (scores, analysis) => {
  const steps = [
    ...scores.topDeductions
      .sort((a, b) => (a.points || 0) - (b.points || 0))
      .map(d => d.reason),
  ];

  if (analysis.keywords.coveragePercent < 40) {
    const missing = analysis.keywords.missingKeywords.slice(0, 3).join(', ');
    if (missing) steps.push(`Add these high-impact keywords: ${missing}`);
  }

  return [...new Set(steps)].slice(0, 5);
};
